SI 4473 Покрытие тестами
AndrewVorotyntsev/photo_app pull request #6
Opened 2023-06-27 07:45 UTC by AndrewVorotyntsev

# Ссылка на задачу

https://jira.surfstudio.ru/browse/SI-4473

# Что было сделано

Было произведено покрытие приложения тестами.

Была написаны:

- Golden тесты

- [x] Экрана списка фото
- [x] Экрана деталей фото

- WM тесты

PhotoListWM

- [x] Создание виджет модели
- [x] Проверка состояния загрузки

PhotoDetailsWM

- [x] Создание виджет модели
- [x] Корректность атрибутов

- Unit тесты

- [x] Interactor
- [x] List model
- [x] Details model
- [x] Color Util

2023-06-27 09:24 UTC, Sadhorsephile requested changes

2023-06-27 09:24 UTC, Sadhorsephile commented on test/unit_test.dart
> +      photoInteractor = PhotoInteractorMock();
для моков следует использовать библиотеку [mocktail](https://pub.dev/packages/mocktail).

1. Определяешь сам мок-файл:
```dart
class PhotoInteractorMock extends Mock implements PhotoInteractor {}
```

2. В `setUp` определяешь, что должен возвращать этот метод при различных входных значениях. Для этого стоит использовать функцию `when`

3. Дёргаешь модельку таким образом, чтобы она дёргала интерактор таким образом, которым ты его настроил и ждёшь результат.

2023-06-27 09:25 UTC, Sadhorsephile commented on test/wm_test.dart
> +        await Future<void>.delayed(const Duration(seconds: 1));
вот это прямо на тоненького - так можно делать только в том случае, если у тебя где-то в этом же тесте задано, что запрос займёт ровно 1 секунду.

2023-06-27 09:25 UTC, Sadhorsephile commented on test/golden_test.dart
в ПРе не хватает самих голденов

2023-06-27 09:34 UTC, AndrewVorotyntsev commented on test/golden_test.dart
В папке test/goldens photo_details.png и photo_list.png же лежат.
Или в описание ПРа вынести?

2023-06-27 10:23 UTC, Sadhorsephile commented on test/golden_test.dart
Хм, почему-то в дифе не появлялись. Увидел, всё ок

2023-06-27 12:29 UTC, AndrewVorotyntsev commented on test/wm_test.dart
> +        await Future<void>.delayed(const Duration(seconds: 1));
Добавил отдельную переменную для этого

2023-06-27 13:34 UTC, AndrewVorotyntsev commented on lib/ui/photo_details/photo_details_screen.dart
> +                          wm.imageUrl == '' ? Colors.red : Colors.transparent,
Получается можно в PhotoDto хранить не String imageUrl ,а ImageProvider. 
На этапе маппинга создавать из ссылки для настоящего интерактора CachedNetworkImageProvider() ,а для мокового будут созданы провайдеры для ассетов.
А на экраны соответственно передаваться созданные провайдеры

2023-06-28 14:26 UTC, Sadhorsephile approved these changes

2023-06-28 14:26 UTC, merged